### ISSUE TITLE
Any plan to upgrade the nuget requirement of mvvmcross to 5.0?

### ISSUE THREAD

**Issue by flyingxu** [aritchie/mvxgoodies#2]
MvvmCross 5 is released, when I tried to upgrade it I found that I'm using this interop package and it requires mvvmcross < 5.

**Comment by aritchie** [comment]
I plan on upgrading when I have time.  Please don't request external library updates in the future.

**Comment by flyingxu** [comment]
I'm sorry if I was not clear. I was talking about the nuspec dependency setting for MvvmCross, which currently is `[4, 5)`. Since now MvvmCross 5 is released and it might be safe to change it to `[4,5]`. What do you think?

**Comment by aritchie** [comment]
I know what you meant, but I still have to test it which I don't have time to do at the moment.
